name: Lint
on: [pull_request]

jobs:
  mx-records:
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '15'

      - run:  git diff $GITHUB_BASE_REF $GITHUB_HEAD_REF HEAD~1 -- emails.txt --no-ext-diff --unified=0 --exit-code -a --no-prefix | egrep "^\+" | tail -n +2 | sed -e 's/^+//g' | node linting/index.js
